;;; org-museum-knowledge-test.el --- Knowledge runtime tests -*- lexical-binding: t -*-

(require 'ert)
(setq load-prefer-newer t)
(require 'org-museum)

(defmacro org-museum-knowledge-test--with-wiki (&rest body)
  `(let* ((org-museum-root-dir (make-temp-file "org-museum-knowledge-" t))
          (org-museum-knowledge--root nil)
          (org-museum-knowledge--queue nil)
          (org-museum-knowledge--analyses nil)
          (org-museum-knowledge--experiences nil)
          (org-museum-knowledge--relations nil)
          (org-museum-knowledge--active nil)
          (org-museum-knowledge--actives nil)
          (org-museum-knowledge--request-buffers nil)
          (org-museum-knowledge--request-timers nil)
          (org-museum-knowledge--batch nil)
          (org-museum-knowledge--batch-log nil)
          (org-museum-knowledge--requested-file nil)
          (org-museum-knowledge--drain nil)
          (org-museum-knowledge--paused nil)
          (org-museum-knowledge-work-mode 'assist)
          (org-museum-knowledge--persist-timer nil)
          (org-museum-knowledge--auto-timer nil)
          (org-museum--index nil))
     (unwind-protect (progn ,@body)
       (when (timerp org-museum-knowledge--persist-timer)
         (cancel-timer org-museum-knowledge--persist-timer))
       (when (timerp org-museum-knowledge--auto-timer)
         (cancel-timer org-museum-knowledge--auto-timer))
       (delete-directory org-museum-root-dir t))))

(ert-deftest org-museum-knowledge-local-backend-uses-explicit-gemma-config ()
  "The local adapter must construct its backend without an unloaded setter."
  (let ((original-require (symbol-function 'require))
        (org-museum-knowledge-local-model "google/gemma-4-e2b")
        (org-museum-knowledge-local-host "127.0.0.1:1234")
        calls)
    (cl-letf (((symbol-function 'require)
               (lambda (feature &rest args)
                 (if (memq feature '(gptel gptel-openai))
                     t (apply original-require feature args))))
              ((symbol-function 'gptel-make-openai)
               (lambda (name &rest args)
                 (push (cons name args) calls)
                 'local-backend)))
      (should (eq 'local-backend (org-museum-knowledge--local-backend)))
      (should (equal '("--noproxy" "*")
                     (plist-get (cdar calls) :curl-args)))
      (should (equal '(google/gemma-4-e2b)
                     (plist-get (cdar calls) :models)))
      (should (equal "127.0.0.1:1234"
                     (plist-get (cdar calls) :host))))))

(ert-deftest org-museum-knowledge-save-queues-without-llm-and-survives-restart ()
  (org-museum-knowledge-test--with-wiki
   (let ((file (expand-file-name "first.org" org-museum-root-dir)))
     (with-temp-file file (insert "#+TITLE: First\nA real fix.\n"))
     (with-temp-buffer
       (insert-file-contents file)
       (setq buffer-file-name file)
       (setq-local org-museum-mode t)
       (cl-letf (((symbol-function 'gptel-request)
                  (lambda (&rest _) (ert-fail "save called AI"))))
         (org-museum-knowledge--on-save)))
     (should (= 1 (length org-museum-knowledge--queue)))
     (org-museum-knowledge--persist-state)
     (setq org-museum-knowledge--root nil
           org-museum-knowledge--queue nil)
     (org-museum-knowledge--ensure)
     (should (= 1 (length org-museum-knowledge--queue)))
     (should (equal "dirty" (alist-get 'status
                                      (car org-museum-knowledge--queue))))
     (org-museum-knowledge--mark-dirty file)
     (should (= 1 (length org-museum-knowledge--queue))))))

(ert-deftest org-museum-knowledge-batch-fills-two-workers-and-cancels-late-work ()
  (org-museum-knowledge-test--with-wiki
   (let ((one (expand-file-name "one.org" org-museum-root-dir))
         (two (expand-file-name "two.org" org-museum-root-dir))
         (calls nil)
         (org-museum-knowledge-max-workers 2))
     (with-temp-file one (insert "#+TITLE: One\nOne note.\n"))
     (with-temp-file two (insert "#+TITLE: Two\nTwo note.\n"))
     (cl-letf (((symbol-function 'org-museum-knowledge--backend)
                (lambda () 'backend))
               ((symbol-function 'org-museum-knowledge--preflight-local)
                (lambda (job _hash _backend _file)
                  (push job calls))))
       (org-museum-knowledge--start-batch (list one two))
       (should (= 2 (length calls)))
       (should (= 2 (length org-museum-knowledge--actives)))
       (should (= 2 (length (alist-get 'jobs org-museum-knowledge--batch))))
       (org-museum-ai-cancel)
       (should-not org-museum-knowledge--actives)
       (should (cl-every (lambda (job) (equal "dirty" (alist-get 'status job)))
                         org-museum-knowledge--queue))))))

(ert-deftest org-museum-knowledge-batch-reuses-current-analysis ()
  (org-museum-knowledge-test--with-wiki
   (let ((file (expand-file-name "cached.org" org-museum-root-dir)))
     (with-temp-file file (insert "#+TITLE: Cached\nStable note.\n"))
     (org-museum-knowledge--ensure)
     (let ((hash (org-museum-knowledge--file-hash file)))
       (setq org-museum-knowledge--analyses
             `(((file . ,file) (hash . ,hash) (summary . "cached")))
             org-museum-knowledge--queue nil)
       (let ((batch (org-museum-knowledge--start-batch (list file))))
         (should (= 1 (alist-get 'reused batch)))
         (should (equal "ready"
                        (alist-get 'status
                                   (org-museum-knowledge--batch-public)))))))))

(ert-deftest org-museum-knowledge-batch-restarts-exhausted-queued-job ()
  "A new selected batch must not strand a job at the retry limit."
  (org-museum-knowledge-test--with-wiki
   (let ((cached (expand-file-name "cached.org" org-museum-root-dir))
         (pending (expand-file-name "pending.org" org-museum-root-dir))
         started)
     (with-temp-file cached (insert "#+TITLE: Cached\nStable note.\n"))
     (with-temp-file pending (insert "#+TITLE: Pending\nRetry note.\n"))
     (org-museum-knowledge--ensure)
     (setq org-museum-knowledge--analyses
           `(((file . ,cached)
              (hash . ,(org-museum-knowledge--file-hash cached))
              (summary . "cached"))))
     (org-museum-knowledge--mark-dirty pending)
     (let ((job (org-museum-knowledge--job pending)))
       (setf (alist-get 'attempts job) (1+ org-museum-knowledge-max-retries)
             (alist-get 'status job) "dirty")
       (cl-letf (((symbol-function 'org-museum-knowledge--backend)
                  (lambda () 'backend))
                 ((symbol-function 'org-museum-knowledge--preflight-local)
                  (lambda (item &rest _) (setq started item))))
         (org-museum-knowledge--start-batch (list cached pending))
         (should (equal pending (alist-get 'file started)))
         (should (= 0 (alist-get 'attempts job)))
         (should (equal "running" (alist-get 'status job))))))))

(ert-deftest org-museum-knowledge-selected-batch-gets-next-worker ()
  "An explicit selection runs before unrelated dirty queue entries."
  (org-museum-knowledge-test--with-wiki
   (let ((unrelated (expand-file-name "unrelated.org" org-museum-root-dir))
         (selected (expand-file-name "selected.org" org-museum-root-dir))
         (org-museum-knowledge-max-workers 1)
         started)
     (with-temp-file unrelated (insert "#+TITLE: Other\n"))
     (with-temp-file selected (insert "#+TITLE: Selected\n"))
     (org-museum-knowledge--mark-dirty unrelated)
     (org-museum-knowledge--mark-dirty selected)
     (cl-letf (((symbol-function 'org-museum-knowledge--backend)
                (lambda () 'backend))
               ((symbol-function 'org-museum-knowledge--preflight-local)
                (lambda (job &rest _)
                  (setq started (alist-get 'file job)))))
       (org-museum-knowledge--start-batch (list selected))
       (should (equal selected started))))))

(ert-deftest org-museum-knowledge-worker-limit-persists-per-wiki ()
  "Changing the worker limit does not start analysis and survives reload."
  (org-museum-knowledge-test--with-wiki
   (let ((org-museum-knowledge-max-workers 2))
     (cl-letf (((symbol-function 'org-museum-knowledge--work-next)
                (lambda () (ert-fail "Worker setting started analysis"))))
       (should (= 4 (org-museum-knowledge--set-max-workers 4))))
     (should (= 4 (alist-get 'maxWorkers
                              (alist-get 'settings
                                         (org-museum-knowledge--read-json
                                          (org-museum-knowledge--state-path))))))
     (setq org-museum-knowledge--root nil
           org-museum-knowledge-max-workers 1)
     (org-museum-knowledge--ensure)
     (should (= 4 org-museum-knowledge-max-workers)))))

(ert-deftest org-museum-knowledge-explicit-analysis-recovers-orphaned-job ()
  (org-museum-knowledge-test--with-wiki
   (let ((file (expand-file-name "first.org" org-museum-root-dir)))
     (with-temp-file file (insert "#+TITLE: First\nSaved note.\n"))
     (org-museum-knowledge--mark-dirty file)
     (let ((job (org-museum-knowledge--job file)))
       (setf (alist-get 'status job) "running")
       (org-museum-knowledge--enqueue-file file)
       (should (equal "dirty" (alist-get 'status job)))))))

(ert-deftest org-museum-knowledge-explicit-analysis-waits-for-active-job ()
  (org-museum-knowledge-test--with-wiki
   (let ((first (expand-file-name "first.org" org-museum-root-dir))
         (selected (expand-file-name "selected.org" org-museum-root-dir))
         (started nil))
     (with-temp-file first (insert "#+TITLE: First\nFirst note.\n"))
     (with-temp-file selected (insert "#+TITLE: Selected\nSelected note.\n"))
     (org-museum-knowledge--mark-dirty first)
     (org-museum-knowledge--mark-dirty selected)
     (let ((first-job (org-museum-knowledge--job first)))
       (setf (alist-get 'status first-job) "running")
       (setq org-museum-knowledge--active first-job)
       (with-temp-buffer
         (setq buffer-file-name selected)
         (org-museum-analyze-current))
       (should (equal selected org-museum-knowledge--requested-file))
       (setq org-museum-knowledge--active nil)
       (setf (alist-get 'status first-job) "done")
       (cl-letf (((symbol-function 'org-museum-knowledge--backend)
                  (lambda () 'local-backend))
                 ((symbol-function 'org-museum-knowledge--preflight-local)
                  (lambda (_job _hash _backend file) (push file started))))
         (org-museum-knowledge--work-next))
       (should (equal (list selected) started))
       (should (null org-museum-knowledge--requested-file))
       (should (equal "running" (alist-get 'status
                                          (org-museum-knowledge--job selected))))
       (org-museum-ai-cancel)))))

(ert-deftest org-museum-knowledge-public-export-requires-current-confirmed-item ()
  (org-museum-knowledge-test--with-wiki
   (let* ((file (expand-file-name "first.org" org-museum-root-dir))
          (page (make-org-museum-page :id "first" :path file))
          (confirmed nil))
     (with-temp-file file (insert "#+TITLE: First\nOriginal note.\n"))
     (org-museum-knowledge--ensure)
     (setq confirmed
           `((file . ,file) (pageId . "first")
             (sourceHash . ,(org-museum-knowledge--file-hash file))
             (problem . "Same failure") (result . "Verified fix")
             (wrongAttempt . "Old workaround") (published . t)))
     (setq org-museum-knowledge--experiences
           (list (append '((problem . "Private finding") (published . nil))
                         `((file . ,file) (pageId . "first")
                           (sourceHash . ,(org-museum-knowledge--file-hash file))))
                 confirmed))
     (let ((html (org-museum-knowledge--page-html page)))
       (should (string-match-p "Verified fix" html))
       (should-not (string-match-p "Private finding" html)))
     (with-temp-file file (insert "#+TITLE: First\nChanged evidence.\n"))
     (should-not (org-museum-knowledge--page-html page)))))

(ert-deftest org-museum-knowledge-recall-finds-prior-confirmed-experience ()
  (org-museum-knowledge-test--with-wiki
   (let* ((file (expand-file-name "first.org" org-museum-root-dir))
          (page (make-org-museum-page :id "first" :path file :title "First")))
     (with-temp-file file (insert "#+TITLE: First\nSQL fix.\n"))
     (setq org-museum--index
           (make-org-museum-index
            :pages (let ((table (make-hash-table :test 'equal)))
                     (puthash "first" page table) table)))
     (org-museum-knowledge--ensure)
     (setq org-museum-knowledge--experiences
           `(((file . ,file) (pageId . "first")
              (sourceHash . ,(org-museum-knowledge--file-hash file))
              (problem . "SQL duplicate rows")
              (result . "Use EXCEPT ALL")
              (wrongAttempt . "Used EXCEPT")
              (verification . "user-confirmed") (published . t))))
     (org-museum-recall "SQL duplicate rows")
     (with-current-buffer "*Org Museum 知识上下文*"
       (should (string-match-p "Use EXCEPT ALL" (buffer-string)))
       (should (string-match-p "Used EXCEPT" (buffer-string)))))))

(ert-deftest org-museum-knowledge-failure-retries-are-bounded ()
  (org-museum-knowledge-test--with-wiki
   (let ((job '((file . "missing.org") (status . "running") (attempts . 0)))
         (org-museum-knowledge-work-mode 'auto)
         (org-museum-knowledge-max-retries 2))
     (org-museum-knowledge--ensure)
     (dotimes (_ 3) (org-museum-knowledge--fail job "offline"))
     (should (equal "failed" (alist-get 'status job)))
     (should (= 3 (alist-get 'attempts job))))))

(ert-deftest org-museum-knowledge-real-export-shows-only-approved-related-experience ()
  (org-museum-knowledge-test--with-wiki
   (let* ((org-museum-scan-dir "pages")
          (org-museum-pages-subdir "pages")
          (org-museum-export-dir "dist/pages")
          (org-museum-shared-export-dir "dist")
          (org-museum-open-browser-after-export nil)
          (pages (expand-file-name "pages" org-museum-root-dir))
          (first (expand-file-name "first.org" pages))
          (second (expand-file-name "second.org" pages)))
     (make-directory pages t)
     (with-temp-file first
       (insert "#+TITLE: SQL duplicate rows\n#+WIKI_ID: first\n"
               "#+CATEGORY: Test\nA confirmed fix.\n"))
     (with-temp-file second
       (insert "#+TITLE: SQL duplicate rows again\n#+WIKI_ID: second\n"
               "#+CATEGORY: Test\nNew task.\n"))
     (org-museum-knowledge--ensure)
     (setq org-museum-knowledge--experiences
           `(((file . ,first) (pageId . "first")
              (sourceHash . ,(org-museum-knowledge--file-hash first))
              (problem . "SQL duplicate rows")
              (result . "Use EXCEPT ALL")
              (wrongAttempt . "Used EXCEPT") (published . t))
             ((file . ,first) (pageId . "first")
              (sourceHash . ,(org-museum-knowledge--file-hash first))
              (problem . "Private finding")
              (result . "Do not publish") (published . nil))
             ((type . "failure-pattern") (file . ,first) (pageId . "first")
              (sourceHash . ,(org-museum-knowledge--file-hash first))
              (problem . "SQL duplicate rows again")
              (cause . "Bag semantics")
              (wrongAttempt . "Used EXCEPT")
              (result . "Use EXCEPT ALL") (scope . "DuckDB queries")
              (verification . "user-confirmed")
              (evidence . ((line . 4) (kind . "org-source")))
              (published . t))
             ((type . "failure-pattern") (file . ,first) (pageId . "first")
              (sourceHash . ,(org-museum-knowledge--file-hash first))
              (problem . "Private SQL failure")
               (cause . "Private cause") (result . "Private fix")
               (published . nil))))
     (setq org-museum-knowledge--relations
           `(((sourcePageId . "first") (targetPageId . "second")
              (sourceFile . ,first) (targetFile . ,second)
              (sourceHash . ,(org-museum-knowledge--file-hash first))
              (targetHash . ,(org-museum-knowledge--file-hash second))
              (type . "supports") (confidence . 0.8)
              (origin . "user-confirmed")
              (evidence . ((excerpt . "PRIVATE_RELATION_EVIDENCE"))))))
     (org-museum-knowledge--persist-derived)
     (org-museum-export-all)
     (let ((html (with-temp-buffer
                   (insert-file-contents
                    (org-museum--export-filename second))
                   (buffer-string))))
       (should (string-match-p "Use EXCEPT ALL" html))
       (should (string-match-p "失败模式" html))
       (should (string-match-p "Bag semantics" html))
       (should (string-match-p "相关原笔记" html))
       (should-not (string-match-p "Do not publish" html))
       (should-not (string-match-p "Private cause" html))
       (should-not (string-match-p "PRIVATE_RELATION_EVIDENCE" html))))))

(ert-deftest org-museum-knowledge-failure-evidence-and-provenance ()
  (org-museum-knowledge-test--with-wiki
   (let* ((file (expand-file-name "failure.org" org-museum-root-dir))
          (page (make-org-museum-page :id "failure" :path file :title "Failure"))
          (table (make-hash-table :test 'equal)))
     (with-temp-file file
       (insert "#+TITLE: Failure\n* Query\n#+begin_src sql\nSELECT 1;\n#+end_src\n"
               "#+RESULTS:\n: 1\n"))
     (puthash "failure" page table)
     (setq org-museum--index (make-org-museum-index :pages table))
     (with-temp-buffer
       (insert-file-contents file)
       (setq buffer-file-name file)
       (org-mode)
       (set-buffer-modified-p nil)
       (setq-local transient-mark-mode t)
       (goto-char (point-min))
       (search-forward "#+RESULTS:")
       (beginning-of-line)
       (set-mark (point))
       (forward-line 2)
       (setq mark-active t)
       (let ((evidence (org-museum-knowledge--evidence-at-point)))
         (should (equal "org-result" (alist-get 'kind evidence)))
         (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                   ((symbol-function 'org-museum--start-background-job)
                    (lambda (&rest _) nil)))
           (org-museum-record-failure evidence "Duplicate SQL rows" "Bag semantics"
                                      "Used EXCEPT" "Use EXCEPT ALL" "DuckDB queries"))))
     (let* ((item (car org-museum-knowledge--experiences))
            (evidence (alist-get 'evidence item))
            (html (org-museum-knowledge--page-html page)))
       (should (equal "failure-pattern" (alist-get 'type item)))
       (should (equal "recorded-result" (alist-get 'verification item)))
       (should (= 6 (alist-get 'line evidence)))
       (should (equal (secure-hash 'sha256 (alist-get 'excerpt evidence))
                      (alist-get 'excerptHash evidence)))
       (should (string-match-p "Bag semantics" html))
       (should (string-match-p "第 6 行" html))
       (should-not (string-match-p "SELECT 1" html)))
     (setq org-museum-knowledge--root nil
           org-museum-knowledge--experiences nil)
     (org-museum-knowledge--ensure)
     (should (equal "failure-pattern"
                    (alist-get 'type (car org-museum-knowledge--experiences))))
     (with-temp-file file (insert "#+TITLE: Changed\n"))
     (should-not (org-museum-knowledge--page-html page)))))

(ert-deftest org-museum-knowledge-failure-needs-approval-and-does-not-self-verify ()
  (org-museum-knowledge-test--with-wiki
   (let* ((file (expand-file-name "failure.org" org-museum-root-dir))
          (page (make-org-museum-page :id "failure" :path file :title "Failure"))
          (table (make-hash-table :test 'equal)))
     (with-temp-file file (insert "#+TITLE: Failure\nA source note.\n"))
     (puthash "failure" page table)
     (setq org-museum--index (make-org-museum-index :pages table))
     (with-temp-buffer
       (insert-file-contents file)
       (setq buffer-file-name file)
       (org-mode)
       (set-buffer-modified-p nil)
       (goto-char (point-min))
       (search-forward "A source note.")
       (let ((evidence (org-museum-knowledge--evidence-at-point)))
         (should (equal "org-source" (alist-get 'kind evidence)))
         (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
           (org-museum-record-failure evidence "Broken" "Cause" "Wrong"
                                      "Fix" "Scope"))
         (should-not org-museum-knowledge--experiences)
         (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                   ((symbol-function 'org-museum--start-background-job)
                    (lambda (&rest _) nil)))
           (org-museum-record-failure evidence "Broken" "Cause" "Wrong"
                                      "Fix" "Scope"))))
     (should (equal "user-confirmed"
                    (alist-get 'verification (car org-museum-knowledge--experiences)))))))

(ert-deftest org-museum-knowledge-failure-reminds-once-and-ranks-first ()
  (org-museum-knowledge-test--with-wiki
   (let* ((old (expand-file-name "old.org" org-museum-root-dir))
          (now (expand-file-name "now.org" org-museum-root-dir))
          (messages nil))
     (with-temp-file old (insert "#+TITLE: SQL duplicate rows\n"))
     (with-temp-file now (insert "#+TITLE: SQL duplicate rows again\n"))
     (org-museum-knowledge--ensure)
     (setq org-museum-knowledge--experiences
           `(((type . "failure-pattern") (file . ,old)
              (sourceHash . ,(org-museum-knowledge--file-hash old))
              (problem . "SQL duplicate rows") (cause . "Bag semantics")
              (wrongAttempt . "Used EXCEPT") (result . "Use EXCEPT ALL")
              (verification . "recorded-result"))))
     (should (> (org-museum-knowledge--experience-score
                 "SQL duplicate rows" (car org-museum-knowledge--experiences))
                (org-museum-knowledge--experience-score
                 "SQL duplicate rows" '((problem . "SQL duplicate rows")))))
     (with-temp-buffer
       (insert-file-contents now)
       (setq buffer-file-name now)
       (setq-local org-museum-mode t)
       (cl-letf (((symbol-function 'message)
                  (lambda (fmt &rest args)
                    (push (apply #'format fmt args) messages)))
                 ((symbol-function 'gptel-request)
                  (lambda (&rest _) (ert-fail "reminder called AI"))))
         (org-museum-knowledge--failure-reminder (current-buffer))
         (org-museum-knowledge--failure-reminder (current-buffer)))
       (should (= 1 (length messages)))
       (should (string-match-p "Used EXCEPT" (car messages))))
     (setf (alist-get 'type (car org-museum-knowledge--experiences)) nil)
     (with-temp-buffer
       (insert-file-contents now)
       (setq buffer-file-name now)
       (setq-local org-museum-mode t)
       (setq messages nil)
       (cl-letf (((symbol-function 'message)
                  (lambda (fmt &rest args)
                    (push (apply #'format fmt args) messages))))
         (org-museum-knowledge--failure-reminder (current-buffer)))
       (should (= 1 (length messages)))))))

(ert-deftest org-museum-knowledge-annotated-relations-improve-recall ()
  (org-museum-knowledge-test--with-wiki
   (let* ((source-file (expand-file-name "source.org" org-museum-root-dir))
          (target-file (expand-file-name "target.org" org-museum-root-dir))
          (source (make-org-museum-page
                   :id "source" :path source-file :title "Source"
                   :links-to '("target")
                   :relation-types '(("target" . "前置依赖"))))
          (target (make-org-museum-page
                   :id "target" :path target-file :title "Target"))
          (table (make-hash-table :test 'equal)))
     (with-temp-file source-file (insert "#+TITLE: Source\n"))
     (with-temp-file target-file (insert "#+TITLE: Target\n"))
     (puthash "source" source table)
     (puthash "target" target table)
     (setq org-museum--index (make-org-museum-index :pages table))
     (let ((relation (car (org-museum-knowledge--annotation-relations))))
       (should (equal "depends-on" (alist-get 'type relation)))
       (should (equal "org-annotation" (alist-get 'origin relation)))
       (should (= 0.95 (alist-get 'confidence relation))))
     (with-temp-buffer
       (insert-file-contents source-file)
       (setq buffer-file-name source-file)
       (org-museum-recall "unrelated query"))
     (with-current-buffer "*Org Museum 知识上下文*"
       (should (string-match-p "前置依赖" (buffer-string)))
       (should (string-match-p "Org 标注" (buffer-string)))
       (should (string-match-p "Target" (buffer-string))))
     (org-museum-relations)
     (with-current-buffer "*Org Museum 笔记关系*"
       (should (string-match-p "有效关系：1" (buffer-string)))
       (should (string-match-p "前置依赖" (buffer-string)))))))

(ert-deftest org-museum-knowledge-confirmed-relation-persists-and-stales ()
  (org-museum-knowledge-test--with-wiki
   (let* ((source-file (expand-file-name "source.org" org-museum-root-dir))
          (target-file (expand-file-name "target.org" org-museum-root-dir))
          (source (make-org-museum-page :id "source" :path source-file :title "Source"))
          (target (make-org-museum-page :id "target" :path target-file :title "Target"))
          (table (make-hash-table :test 'equal)))
     (with-temp-file source-file
       (insert "#+TITLE: Source\nEvidence for relation.\n"))
     (with-temp-file target-file (insert "#+TITLE: Target\n"))
     (puthash "source" source table)
     (puthash "target" target table)
     (setq org-museum--index (make-org-museum-index :pages table))
     (with-temp-buffer
       (insert-file-contents source-file)
       (setq buffer-file-name source-file)
       (org-mode)
       (set-buffer-modified-p nil)
       (goto-char (point-min))
       (search-forward "Evidence for relation.")
       (let ((evidence (org-museum-knowledge--evidence-at-point)))
         (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) nil)))
           (org-museum-relate-current "target" "supports" 0.8 evidence))
         (should-not org-museum-knowledge--relations)
         (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
           (org-museum-relate-current "target" "supports" 0.8 evidence))))
     (should (= 1 (length org-museum-knowledge--relations)))
     (should (org-museum-knowledge--relation-current-p
              (car org-museum-knowledge--relations)))
     (with-temp-buffer
       (insert-file-contents source-file)
       (setq buffer-file-name source-file)
       (org-museum-recall "unrelated query"))
     (with-current-buffer "*Org Museum 知识上下文*"
       (should (string-match-p "用户确认" (buffer-string)))
       (should (string-match-p "Target" (buffer-string))))
     (setq org-museum-knowledge--root nil
           org-museum-knowledge--relations nil)
     (org-museum-knowledge--ensure)
     (should (= 1 (length org-museum-knowledge--relations)))
     (with-temp-file target-file (insert "#+TITLE: Changed\n"))
     (should-not (org-museum-knowledge--effective-relations))
     (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
       (org-museum-relation-remove
        (alist-get 'id (car org-museum-knowledge--relations))))
     (should-not org-museum-knowledge--relations))))

(ert-deftest org-museum-knowledge-conflicts-are-reviewable-not-resolved ()
  (org-museum-knowledge-test--with-wiki
   (let* ((file (expand-file-name "first.org" org-museum-root-dir))
          (other (expand-file-name "second.org" org-museum-root-dir))
          (relations '(((sourcePageId . "a") (targetPageId . "b")
                        (type . "supports"))
                       ((sourcePageId . "a") (targetPageId . "b")
                        (type . "contradicts"))
                       ((sourcePageId . "a") (targetPageId . "b")
                        (type . "depends-on"))
                       ((sourcePageId . "b") (targetPageId . "a")
                        (type . "depends-on")))))
     (with-temp-file file (insert "#+TITLE: First\n"))
     (with-temp-file other (insert "#+TITLE: Second\n"))
     (org-museum-knowledge--ensure)
     (setq org-museum-knowledge--experiences
           `(((file . ,file)
              (sourceHash . ,(org-museum-knowledge--file-hash file))
              (problem . "Same problem") (result . "Fix A") (published . t))
             ((file . ,other)
              (sourceHash . ,(org-museum-knowledge--file-hash other))
              (problem . "Same problem") (result . "Fix B") (published . t))))
     (let ((kinds (mapcar #'car (org-museum-knowledge--conflicts relations))))
       (should (member 'opposed-relations kinds))
       (should (member 'circular-dependency kinds))
       (should (member 'divergent-fixes kinds)))
     (should (org-museum-knowledge--pair-conflicting-p "a" "b" relations))
     (should (equal "influences"
                    (org-museum-knowledge--relation-type-from-label "启发影响")))
     (should (equal "part-of"
                    (org-museum-knowledge--relation-type-from-label "属于")))
     (let ((table (make-hash-table :test 'equal)))
       (puthash "a" (make-org-museum-page :id "a" :path file :title "First") table)
       (puthash "b" (make-org-museum-page :id "b" :path other :title "Second") table)
       (setq org-museum--index (make-org-museum-index :pages table))
       (setq org-museum-knowledge--relations
             (mapcar (lambda (relation)
                       (append relation
                               `((sourceFile . ,(if (equal (alist-get 'sourcePageId relation) "a")
                                                    file other))
                                 (targetFile . ,(if (equal (alist-get 'targetPageId relation) "b")
                                                    other file))
                                 (sourceHash . ,(org-museum-knowledge--file-hash
                                                 (if (equal (alist-get 'sourcePageId relation) "a")
                                                     file other)))
                                 (targetHash . ,(org-museum-knowledge--file-hash
                                                 (if (equal (alist-get 'targetPageId relation) "b")
                                                     other file)))
                                 (confidence . 0.8) (origin . "user-confirmed"))))
                     relations))
       (with-temp-buffer
         (insert-file-contents file)
         (setq buffer-file-name file)
         (org-museum-recall "same problem"))
       (with-current-buffer "*Org Museum 知识上下文*"
         (should (string-match-p "待复核：同一对笔记" (buffer-string)))))
     (should (= 2 (length org-museum-knowledge--experiences))))))

(provide 'org-museum-knowledge-test)
